package mock02.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "hoctructuyen")
public class Course implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idCourse;
	private String courseName;
	private String description;
	private Set<Member> members = new HashSet<Member>();
	private Set<Assignment> assignments = new HashSet<Assignment>();
	private Set<Schedule> schedules = new HashSet<Schedule>();
	private Set<Subject> subjects = new HashSet<Subject>();
	private Set<Discussion> discussions = new HashSet<Discussion>();

	public Course() {
	}

	public Course(String courseName) {
		this.courseName = courseName;
	}

	public Course(String courseName, String description, Set<Member> members, Set<Assignment> assignments,
			Set<Schedule> schedules, Set<Subject> subjects, Set<Discussion> discussions) {
		this.courseName = courseName;
		this.description = description;
		this.members = members;
		this.assignments = assignments;
		this.schedules = schedules;
		this.subjects = subjects;
		this.discussions = discussions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcourse", unique = true, nullable = false)
	public Integer getIdCourse() {
		return this.idCourse;
	}

	public void setIdCourse(Integer idCourse) {
		this.idCourse = idCourse;
	}

	@Column(name = "coursename", nullable = false, length = 100)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Member> getMembers() {
		return this.members;
	}

	public void setMembers(Set<Member> members) {
		this.members = members;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Assignment> getAssignments() {
		return this.assignments;
	}

	public void setAssignments(Set<Assignment> assignments) {
		this.assignments = assignments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course", cascade = CascadeType.PERSIST)
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Subject> getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set<Subject> subjects) {
		this.subjects = subjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Discussion> getDiscussions() {
		return discussions;
	}

	public void setDiscussions(Set<Discussion> discussions) {
		this.discussions = discussions;
	}

}
