package mock02.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Discussion generated by hbm2java
 */
@Entity
@Table(name = "discussion", catalog = "hoctructuyen")
public class Discussion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idDiscussion;
	private Member member;
	private String title;
	private Course course;
	private String contentDiscussion;
	private Set<Participation> participations = new HashSet<Participation>();

	public Discussion() {
	}

	public Discussion(Member member, String title, String contentDiscussion, Course course) {
		this.member = member;
		this.title = title;
		this.contentDiscussion = contentDiscussion;
		this.course = course;
	}

	public Discussion(Member member, String title, String contentDiscussion, Set<Participation> participations) {
		this.member = member;
		this.title = title;
		this.contentDiscussion = contentDiscussion;
		this.participations = participations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "iddiscussion", unique = true, nullable = false)
	public Integer getIdDiscussion() {
		return this.idDiscussion;
	}

	public void setIdDiscussion(Integer idDiscussion) {
		this.idDiscussion = idDiscussion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmember")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "title", nullable = false, length = 300)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "contentdiscussion", nullable = false, length = 700)
	public String getContentDiscussion() {
		return this.contentDiscussion;
	}

	public void setContentDiscussion(String contentDiscussion) {
		this.contentDiscussion = contentDiscussion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discussion")
	public Set<Participation> getParticipations() {
		return this.participations;
	}

	public void setParticipations(Set<Participation> participations) {
		this.participations = participations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcourse", nullable = false)
	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

}
