package mock02.model;

import java.sql.Blob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "hoctructuyen")
public class Resource implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idResource;
	private Lecture lecture;
	private String type;
	private String resourceTitle;
	private Blob resourceContent;

	public Resource() {
	}

	public Resource(Lecture lecture, String type, String resourceTitle) {
		this.lecture = lecture;
		this.type = type;
		this.resourceTitle = resourceTitle;
	}

	public Resource(Lecture lecture, String type, String resourceTitle, Blob resourceContent) {
		this.lecture = lecture;
		this.type = type;
		this.resourceTitle = resourceTitle;
		this.resourceContent = resourceContent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idresource", unique = true, nullable = false)
	public Integer getIdResource() {
		return this.idResource;
	}

	public void setIdResource(Integer idResource) {
		this.idResource = idResource;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
	@JoinColumn(name = "idlecture", nullable = false)
	public Lecture getLecture() {
		return this.lecture;
	}

	public void setLecture(Lecture lecture) {
		this.lecture = lecture;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "resourcetitle", nullable = false, length = 100)
	public String getResourceTitle() {
		return this.resourceTitle;
	}

	public void setResourceTitle(String resourceTitle) {
		this.resourceTitle = resourceTitle;
	}

	@Column(name = "resourcecontent", length = 100)
	public Blob getResourceContent() {
		return this.resourceContent;
	}

	public void setResourceContent(Blob resourceContent) {
		this.resourceContent = resourceContent;
	}
}
