package mock02.model;

import java.sql.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule", catalog = "hoctructuyen")
public class Schedule implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idSchedule;
	private Course course;
	private String title;
	private String content;
	private String footer;
	private Date date;
	private Boolean important;

	public Schedule() {
	}

	public Schedule(Course course, String title, String footer, Date date) {
		this.course = course;
		this.title = title;
		this.footer = footer;
		this.date = date;
	}

	public Schedule(Course course, String title, String content, String footer, Date date, Boolean important) {
		this.course = course;
		this.title = title;
		this.content = content;
		this.footer = footer;
		this.date = date;
		this.important = important;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idschedule", unique = true, nullable = false)
	public Integer getIdSchedule() {
		return this.idSchedule;
	}

	public void setIdSchedule(Integer idSchedule) {
		this.idSchedule = idSchedule;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
	@JoinColumn(name = "idcourse", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "title", nullable = false, length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 800)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "footer", nullable = false, length = 100)
	public String getFooter() {
		return this.footer;
	}

	public void setFooter(String footer) {
		this.footer = footer;
	}

	@Column(name = "date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "important")
	public Boolean getImportant() {
		return this.important;
	}

	public void setImportant(Boolean important) {
		this.important = important;
	}

}
