package mock02.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "hoctructuyen")
public class Subject implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idSubject;
	private Course course;
	private String subjectName;
	private Set<Lecture> lectures = new HashSet<Lecture>();

	public Subject() {
	}

	public Subject(Course course, String subjectName) {
		this.course = course;
		this.subjectName = subjectName;
	}

	public Subject(Course course, String subjectName, Set<Lecture> lectures) {
		this.course = course;
		this.subjectName = subjectName;
		this.lectures = lectures;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idsubject", unique = true, nullable = false)
	public Integer getIdSubject() {
		return this.idSubject;
	}

	public void setIdSubject(Integer idSubject) {
		this.idSubject = idSubject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcourse", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "subjectname", nullable = false, length = 200)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "subject", cascade = CascadeType.PERSIST)
	@OrderBy("idLecture")
	public Set<Lecture> getLectures() {
		return this.lectures;
	}

	public void setLectures(Set<Lecture> lectures) {
		this.lectures = lectures;
	}

}
